name: 'Markdown action: create indexes'
description: 'Creates indexes pages for a markdown styled wiki'
branding:
  icon: activity
  color: green
inputs:
  folder:
    description: The folder path to start at
    required: false
    default: "${{ github.workspace }}"
  filename:
    description: The name of the file, default to 'index.md'
    required: false
    default: index.md
runs:
  using: 'node16'
  main: 'dist/index.js'
