name: 'Markdown action: create indexes'
description: 'Creates indexes pages for a markdown styled wiki'
inputs:
  folder:
    description: The folder path to start at
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'