name: 📋 PR
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build:
    name: 📦🔍 Build Check
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v7

      - name: 🛠️ Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: 🛠️ Setup Project
        run: npm ci

      - name: 🛠️ Build
        run: npm run compile
