# This is a basic workflow to help you get started with Actions
name: Test script

# Controls when the action will run. 
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - uses: DaanV2/Markdown-Action-Create-Indexes@main
        with: 
          folder: ${{github.workspace}}
